#!/bin/bash
#
#   This file echoes a bunch of color codes to the 
#   terminal to demonstrate what's available.  Each 
#   line is the color code of one forground color,
#   out of 17 (default + 16 escapes), followed by a 
#   test use of that color on all nine background 
#   colors (default + 8 escapes).
#

T='gYw'   # The test text

echo -e "\n                 40m     41m     42m     43m\
44m     45m     46m     47m";

for FGs in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
    '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
    '  36m' '1;36m' '  37m' '1;37m';
do FG=${FGs// /}
    echo -en " $FGs \033[$FG  $T  "
    for BG in 40m 41m 42m 43m 44m 45m 46m 47m;
    do echo -en "$EINS \033[$FG\033[$BG  $T  \033[0m";
    done
    echo;
done
echo

#script 2

COLS="$(xrdb -query| grep -Ei [.*]color[01-9] | sort -n -tr -k2  | tr -d [*[:blank:]])"

for i in {0..7}; do echo -en "\e[0;3${i}m$(echo -e "$COLS" | sed -n $(($i+1))'p' | cut -d ':' -f 1)\e[0m\t"; done; echo
for i in {0..7}; do echo -en "\e[0;3${i}m$(echo -e "$COLS" | sed -n $(($i+1))'p' | cut -d ':' -f 2)\e[0m\t\t"; done; echo
for i in {0..7}; do echo -en "\e[0;3${i}m▉▉▉▉▉▉▉\t\t"; done; echo
for i in {0..7}; do echo -en "\e[0;9${i}m$(echo -e "$COLS" | sed -n $(($i+9))'p' | cut -d ':' -f 1)\e[0m\t"; done; echo
for i in {0..7}; do echo -en "\e[0;9${i}m$(echo -e "$COLS" | sed -n $(($i+9))'p' | cut -d ':' -f 2)\e[0m\t\t"; done; echo
for i in {0..7}; do echo -en "\e[0;9${i}m▉▉▉▉▉▉▉\t\t"; done; echo -e "\033[0m"
echo -en "foreground: ▉▉▉▉▉▉▉▉▉▉▉ \n"

#script 3

initializeANSI()
{
    esc=""

    blackf="${esc}[30m";   redf="${esc}[31m";    greenf="${esc}[32m"
    yellowf="${esc}[33m"   bluef="${esc}[34m";   purplef="${esc}[35m"
    cyanf="${esc}[36m";    whitef="${esc}[37m"
    
    blackb="${esc}[40m";   redb="${esc}[41m";    greenb="${esc}[42m"
    yellowb="${esc}[43m"   blueb="${esc}[44m";   purpleb="${esc}[45m"
    cyanb="${esc}[46m";    whiteb="${esc}[47m"

    boldon="${esc}[1m";    boldoff="${esc}[22m"
    italicson="${esc}[3m"; italicsoff="${esc}[23m"
    ulon="${esc}[4m";      uloff="${esc}[24m"
    invon="${esc}[7m";     invoff="${esc}[27m"

    reset="${esc}[0m"
}

initializeANSI

cat << EOF

 ${redf}   ▄████▄     ${greenf}   ▄████▄     ${yellowf}   ▄████▄     ${bluef}   ▄████▄     ${purplef}   ▄████▄     ${cyanf}   ▄████▄   
 ${redf}  ██▀▀▀▀██    ${greenf}  ██▀▀▀▀██    ${yellowf}  ██▀▀▀▀██    ${bluef}  ██▀▀▀▀██    ${purplef}  ██▀▀▀▀██    ${cyanf}  ██▀▀▀▀██
 ${redf}  █      █    ${greenf}  █      █    ${yellowf}  █      █    ${bluef}  █      █    ${purplef}  █      █    ${cyanf}  █      █   
 ${redf} █  ▄▀▀▄  █   ${greenf} █  ▄▀▀▄  █   ${yellowf} █  ▄▀▀▄  █   ${bluef} █  ▄▀▀▄  █   ${purplef} █  ▄▀▀▄  █   ${cyanf} █  ▄▀▀▄  █ 
 ${redf}█ ▄█▬▄▄▬█▄ █  ${greenf}█ ▄█▬▄▄▬█▄ █  ${yellowf}█ ▄█▬▄▄▬█▄ █  ${bluef}█ ▄█▬▄▄▬█▄ █  ${purplef}█ ▄█▬▄▄▬█▄ █  ${cyanf}█ ▄█▬▄▄▬█▄ █
 
 ${boldon}
 ${redf}   ▄████▄     ${greenf}   ▄████▄     ${yellowf}   ▄████▄     ${bluef}   ▄████▄     ${purplef}   ▄████▄     ${cyanf}   ▄████▄   
 ${redf}  ██▀▀▀▀██    ${greenf}  ██▀▀▀▀██    ${yellowf}  ██▀▀▀▀██    ${bluef}  ██▀▀▀▀██    ${purplef}  ██▀▀▀▀██    ${cyanf}  ██▀▀▀▀██
 ${redf}  █      █    ${greenf}  █      █    ${yellowf}  █      █    ${bluef}  █      █    ${purplef}  █      █    ${cyanf}  █      █   
 ${redf} █  ▄▀▀▄  █   ${greenf} █  ▄▀▀▄  █   ${yellowf} █  ▄▀▀▄  █   ${bluef} █  ▄▀▀▄  █   ${purplef} █  ▄▀▀▄  █   ${cyanf} █  ▄▀▀▄  █ 
 ${redf}█ ▄█▬▄▄▬█▄ █  ${greenf}█ ▄█▬▄▄▬█▄ █  ${yellowf}█ ▄█▬▄▄▬█▄ █  ${bluef}█ ▄█▬▄▄▬█▄ █  ${purplef}█ ▄█▬▄▄▬█▄ █  ${cyanf}█ ▄█▬▄▄▬█▄ █
 ${reset}
 ****************** Building blocks: █ ▓ ▒ ░ ▄ ▀ ▐ ▌ ●  ═ ║ ╔ ╦ ╗ ╚ ╩ ╝ ■ ▬ ▲ ▼ ◄ ► 

EOF

#script 4

xdef="/etc/X11/Xresources"

colors=( $( sed -re '/^!/d; /^$/d; /^#/d; s/(\*color)([0-9]):/\10\2:/g;' $xdef | grep 'color[01][0-9]:' | sort | sed  's/^.*: *//g' ) )

echo -e "\e[1;37m 
 Black    Red      Green    Yellow   Blue     Magenta   Cyan    White   
──────────────────────────────────────────────────────────────────────\e[0m"
for i in {0..7}; do echo -en "\e[$((30+$i))m ${colors[i]} \e[0m"; done
echo
for i in {8..15}; do echo -en "\e[1;$((22+$i))m ${colors[i]} \e[0m"; done
echo -e "\n"
