#!/bin/bash
# Edgar Uriel Domínguez Espinoza
# edgar_uriel84@NOSPAM.gmx.com

[[ -z "$DISPLAY" ]] && exit 1

if [[ -f "$HOME/.dwm/dmenurc" ]]; then
    . "$HOME/.dwm/dmenurc"
else
    DMENU='dmenu -i'
fi

## Functions
# https://crunchbang.org/forums/viewtopic.php?pid=428517#p428517
function reloadGTK(){
    python2 - <<END
import gtk

events=gtk.gdk.Event(gtk.gdk.CLIENT_EVENT)
data=gtk.gdk.atom_intern("_GTK_READ_RCFILES", False)
events.data_format=8
events.send_event=True
events.message_type=data
events.send_clientmessage_toall()

END
}
## Functions


CHOICE=$(echo -e "1: Screenshot\n2: Screenshot Window\n3: Take Picture\n4: Show Camera\n5: Reload Xresources\n6:Switch theme" | $DMENU | cut -d ':' -f 1)

[[ -z "$CHOICE" ]] && exit 1

case "$CHOICE" in
    1) screenshot -m root &	;;
    2) screenshot -m window &	;;
    3) webcam -r 2 ;;
    4) webcam -r 1 ;;
    5) xrdb -merge /etc/X11/Xresources ;;
    6) sed -i -e 's/Light/Dark/g' -e t -e 's/Dark/Light/g' $HOME/.gtkrc-2.0
       reloadGTK ;;
    7) ;;
    8) ;;
    9) ;;
    0) ;;
    *) exit 1                 ;;
esac
