#!/bin/bash
# Edgar Uriel Domínguez Espinoza
# edgar_uriel84@NOSPAM.gmx.com

[[ -z "$DISPLAY" ]] && exit 1

if [[ -f "$HOME/.dwm/dmenurc" ]]; then
    . "$HOME/.dwm/dmenurc"
else
    DMENU='dmenu -i'
fi

CHOICE=$(echo -e "1: Tools\n2: Umount\n3: Change Wallpaper\n4:Restart dstatus\n5:MoC\n6:Toggle Touchpad\n7: Reload Xresources\n8: Kill app\n9: Reboot\n0: Shutdown" | $DMENU | cut -d ':' -f 1)

[[ -z "$CHOICE" ]] && exit 1

case "$CHOICE" in
    1) dtools &               ;;
    2) dumount &              ;;
    3) dwall &                ;;
    4) killall dstatus
       dstatus                ;;
    5) dmoc &                 ;;
    6) toggle-touchpad        ;;
    7) xrdb -merge /etc/X11/Xresources ;;
    8) xkill &                ;;
    9) sudo shutdown -r now & ;;
    0) sudo shutdown -h now & ;;
    *) exit 1                 ;;
esac
