#!/bin/bash
# Edgar Uriel Domínguez Espinoza
# edgar_uriel84@NOSPAM.gmx.com

# This is a small script is useful with MoC and clyrics (https://github.com/trizen/clyrics)
# is needed for get lyrics from Internet. In fact clyrics could be enough for you

help() {
    echo "Show lyrics on console"
    echo "lyrics [OPCIONS]"
    echo "Opcions:"
    echo "-a <ARTIST>"
    echo "-t <TITLE>"
    echo "-d <DIR>"
    exit 0
}

# Begin Script
ARTIST=`mocp -i | awk '/^Artist:/ { $1=""; print $0 }' | sed -e 's/^ *//g' -e 's/ *$//g'`
TITLE=`mocp -i | awk '/^SongTitle:/ { $1=""; print $0 }' | sed -e 's/^ *//g' -e 's/ *$//g'`
DIR="$HOME/.lyrics"
if [[ $1 == "-h" ]]; then
    help
else
    while getopts a:t:d: option
    do
	case "${option}" in
            a) ARTIST=${OPTARG} ;;
            t) TITLE=${OPTARG} ;;
            d) DIR=${OPTARG} ;;
	esac
    done
    FILE="$DIR/$ARTIST - $TITLE.txt"
    if [[ -f "$FILE" ]]; then
	exec $PAGER "$FILE"
    else
	exec clyrics "$ARTIST" "$TITLE" | "$PAGER"
    fi
    exit 0
fi
# End Script 
