#!/bin/bash

# Copyright (C) 2013, Edgar Uriel Domínguez Espinoza

# screencast is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.

# screencast is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with screencast; if not, see <http://www.gnu.org/licenses/>
# or write to the Free Software Foundation, Inc., 51 Franklin St, Fifth
# Floor, Boston, MA 02110-1301 USA

help() {
    echo "Script que realiza un screencast"
    echo "screencast [OPCIONES]"
    echo "Opciones:"
    echo "-f <FILE>    Archivo donde se guardará la imagen. El formato será:"
    echo "             <FILE>-YYYYMMDD-HHMMSS por default es: webcam"
    exit 0
}
# Begin Script
FILE=screencast
# RESOLUTION="$(xrandr  | grep \* | cut -d' ' -f4)"
RESOLUTION="$(xrandr | grep '*' | sed 's/\s*\([0-9x]*\).*/\1/')"

if [[ $1 == "-h" ]]; then
    help
else
    while getopts f: option
    do
	case "${option}"
            in
            f) FILE=${OPTARG}   ;;
	esac
    done
    FILE_NAME=$HOME/Desktop/$FILE-`date +%Y%m%d-%H%M%S`
    [[ -z "$DISPLAY" ]] && exit 1
    avconv -f x11grab -s $RESOLUTION -i $DISPLAY -f alsa -ac 2 -i default -async 1 -acodec flac -vcodec libx264 -preset ultrafast -crf 0 -threads 0 $FILE_NAME.mkv
    exit 0
fi 
