#!/bin/bash

WORK_DIR="/sys/class/power_supply"
CAPACITY=`/bin/cat $WORK_DIR/BAT0/capacity`
STATUS=`/bin/cat $WORK_DIR/BAT0/status`
#ACAD=`/bin/cat $WORK_DIR/AC/online`
CURRENT=`/bin/cat $WORK_DIR/BAT0/charge_now`
FULL=`/bin/cat $WORK_DIR/BAT0/charge_full`
STATE=$(( $CURRENT * 100 / $FULL))

if [ $STATE -lt 100 ]
then
    echo -n ":: $STATE%"
else
    echo -n ":: =$STATUS"
fi
