#!/bin/bash

ID=`xinput | sed -nre '/TouchPad|Touchpad/s/.*id=([0-9]*).*/\1/p'`
STATE=`xinput list-props $ID|grep 'Device Enabled'|awk '{print $4}'`

if [ $STATE -eq 1 ]
then
    xinput disable $ID
else
    xinput enable $ID
fi
